// GNU LESSER GENERAL PUBLIC LICENSE Version 2.1, February 1999

// WARNING: This file has automatically been generated on Wed, 19 Sep 2018 15:16:06 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package libmodbus

/*
#cgo LDFLAGS: -lmodbus
#include "config.h"
#include "modbus.h"
#include "modbus-private.h"
#include "modbus-rtu.h"
#include "modbus-rtu-private.h"
#include "modbus-tcp.h"
#include "modbus-tcp-private.h"
#include "modbus-version.h"
#include "errno.h"
#include "stdio.h"
#include "stdlib.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// ErrorRecoveryMode as declared in libmodbus/modbus.h:177
type ErrorRecoveryMode int32

// ErrorRecoveryMode enumeration from libmodbus/modbus.h:177
const ()

const ()
