// GNU LESSER GENERAL PUBLIC LICENSE Version 2.1, February 1999

// WARNING: This file has automatically been generated on Wed, 19 Sep 2018 15:16:06 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package modbus provides Go bindings for libmodbus implementation by Stephane Raimbault
*/
package libmodbus
