// GNU LESSER GENERAL PUBLIC LICENSE Version 2.1, February 1999

// WARNING: This file has automatically been generated on Wed, 19 Sep 2018 15:16:06 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package libmodbus

/*
#cgo LDFLAGS: -lmodbus
#include "config.h"
#include "modbus.h"
#include "modbus-private.h"
#include "modbus-rtu.h"
#include "modbus-rtu-private.h"
#include "modbus-tcp.h"
#include "modbus-tcp-private.h"
#include "modbus-version.h"
#include "errno.h"
#include "stdio.h"
#include "stdlib.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// T as declared in libmodbus/modbus.h:155
type T C.modbus_t

// MappingT as declared in libmodbus/modbus.h:170
type MappingT struct {
	NbBits              int32
	StartBits           int32
	NbInputBits         int32
	StartInputBits      int32
	NbInputRegisters    int32
	StartInputRegisters int32
	NbRegisters         int32
	StartRegisters      int32
	TabBits             []byte
	TabInputBits        []byte
	TabInputRegisters   []uint16
	TabRegisters        []uint16
	ref9cc1d52a         *C.modbus_mapping_t
	allocs9cc1d52a      interface{}
}
